version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling code
      - cd app
      - go get encoding/json
      - go get fmt
      - go get io/ioutil
      - go get os
      - go get time
      - go get github.com/aws/aws-sdk-go/service/iam
      - go get github.com/leonegeo/mfacache
      - go build mfacache.go
      - export MFACACHE=1 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - builds*/**