version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling code
      - cd app
      - go build mfacache.go
      - export MFACACHE=1 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - mfacache